version: '3.9'

services:

  dbpostgre:
    image: postgres:15.4-alpine3.18
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersenha
      POSTGRES_DB: "katana_studiodb_user"
    volumes:
      - ./migrate/0001_create_db_pgsql.up.sql:/docker-entrypoint-initdb.d/db.sql
      - ./tmp_data/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - user-bridge

networks:
  user-bridge:
    name: user-bridge
