version: '3.9'

services:
  dbpostgre:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersenha
      POSTGRES_DB: seradb
    volumes:
      - ./tmp_data/postgres_data:/var/lib/postgresql/data
      - ./migrate/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - user-bridge

networks:
  user-bridge:
    name: user-bridge
